# Generated by Django 4.1.7 on 2023-05-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=16)),
                ('contact', models.PositiveIntegerField()),
                ('interest', models.FloatField(max_length=4)),
                ('amt', models.PositiveIntegerField()),
                ('months', models.PositiveIntegerField()),
                ('Collateral', models.CharField(choices=[('Gold', 'Gold'), ('Vehicles', 'Vehicles'), ('Land Docs', 'Land Docs'), ('Other Valuables', 'Other Valuables')], max_length=100)),
                ('Verified', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Verified?')),
                ('Address', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='Custimg')),
            ],
            options={
                'db_table': 'cust_table',
            },
        ),
    ]
